config/routes.rb
Rails.application.routes.draw do
  namespace :server_side_events do
    get  ''             , action: :index
    get  'current_time'
    get  'events'
    get  'fire_event'
  end

  root 'server_side_events#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/server_side_events_controller.rb
class ServerSideEventsController < ApplicationController
  include ActionController::Live

  def index
  end

  def current_time
    respond_to do |format|
      format.html { sse_current_time if sse? }
      format.sse  { sse_current_time }
    end
  end

  def events
    respond_to do |format|
      format.html { sse_events if sse? }
      format.sse  { sse_events }
    end
  end

  def fire_event
    ActiveSupport::Notifications.instrument('sse_event')

    render nothing: true
  end

  private

  def sse_events
    response.headers['Content-Type'] = 'text/event-stream'
    sse = SSE.new(response.stream)

    sse.write message: 'starting'

    ActiveSupport::Notifications.subscribe('sse_event') do |*args|
      sse.write message: 'event received'
    end

    sleep
  rescue IOError => e
    raise e unless e.message == 'closed stream'

    logger.info sse_closed_stream_message(request)
  ensure
    sse.close
  end

  def sse_current_time
    response.headers['Content-Type'] = 'text/event-stream'
    sse = SSE.new(response.stream)

    timeout = params[:timeout].try(:to_i)
    elapsed = 0

    loop do
      sse.write time: Time.now
      elapsed += (sleep 1)

      break if timeout && elapsed >= timeout
    end

  rescue IOError => e
    raise e unless e.message == 'closed stream'

    logger.info sse_closed_stream_message(request)
  ensure
    sse.close
  end

  # Closed SSE stream GET "/session/new" for 127.0.0.1 at 2012-09-26 14:51:42 -0700
  def sse_closed_stream_message(request)
    '  Closed SSE stream %s "%s" for %s at %s' % [
      request.request_method,
      request.filtered_path,
      request.ip,
      Time.now.to_default_s ]
  end

  def sse?
    params[:_sse] == 'true'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/server_side_events_helper.rb
module ServerSideEventsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ServerSideEvents</title>
    <%= ::NewRelic::Agent.browser_timing_header rescue '' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class="application-layout <%= controller_name.dasherize %>-controller <%= action_name.dasherize %>-action">
    <%= yield %>
  </body>
</html>

app/views/server_side_events/current_time.html.erb
<div id="status"></div>
<div id="current_time"></div>

app/views/server_side_events/events.html.erb
<div id="status"></div>
<div id="stream"></div>

app/views/server_side_events/index.html.erb
<%= link_to server_side_events_current_time_path, server_side_events_current_time_path %>
<%= link_to server_side_events_events_path, server_side_events_events_path %>